# Generated by Django 3.0.2 on 2020-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender_recog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
            ],
        ),
    ]
